-   id: kustomize_check
    name: kustomize docker image
    description: Kustomize Check from Docker Image
    entry: rtrox/kustomize_check:v5.8.0 kustomize build
    language: docker_image
    args: [overlay/production-us]
    always_run: false
    pass_filenames: false
    files: ((^|/)*.(ya?ml)$)
-   id: kustomize_check_local
    name: kustomize docker local
    description: Kustomize Check via Local Docker Build
    entry: kustomize build
    language: docker
    args: [overlay/production-us]
    always_run: false
    pass_filenames: false
    files: ((^|/)*.(ya?ml)$)
-   id: kustomize_check_system
    name: Kustomize Check using installed kustomize binary
    entry: kustomize build
    language: system
    args: [overlay/production-us]
    always_run: false
    pass_filenames: false
    files: ((^|/)*.(ya?ml)$)